name: Generate 8-bit Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run 8-bit image generation script
      run: |
        python generate_8bit_image.py input_image.png output_image.png 16

    - name: Upload output image
      uses: actions/upload-artifact@v3
      with:
        name: output_image
        path: output_image.png
